### ISSUE TITLE
Question about "FreezePadding"

### ISSUE THREAD

**Issue by sarwart** [Optum/retain-keras#14]
Hi!

I am trying to understand your code and I have a quick question. The classes FreezePadding (or FreezePadding_Non_Negative -- retain_train.py) is defined but the __call__ function is never used. I can notice an instance creation while defining the embedding layer but I could find a code where the weights are being updated. Also , I am unable to understand it's purpose.

**Comment by tRosenflanz** [comment]
Hi! 

Freeze padding is a constraint on embedding weights. It forces last index (padding index) of the embedding layer to be all 0s - this means that during downstream summation the padding embedding is eliminated. If this constraint is not used, padding will have an impact on the predictions which is suboptimal since different batch size values will produce different results for the same record. Non_neg constraint also adds non-negativity constraint on embedding values to force only positive contributions for different codes (this works similar to L1 constraint and empirically consistently produces better results)

As for call function it gets automatically invoked by Keras during weight updates

**Comment by sarwart** [comment]
Thank you tRosemflanz.

Also,  is--num_codes basically the number of total codes present in .types file? Why 1 is added in the embedding layer for the first argument ( _L.Embedding(**ARGS.num_codes+1**, ARGS.emb_size, name='embedding',                                    embeddings_constraint=embeddings_constraint)(codes)_)?

**Comment by tRosenflanz** [comment]
Yep, it is. Extra code is added for padding!

**Comment by sarwart** [comment]
I apologize for the silly questions but I am trying to understand the code.  In L.Embedding extra 1 is for padding, whose weights  are forced to 0 in Freezepadding function during weight updates. Right?

**Comment by tRosenflanz** [comment]
Not a silly question at all. That's exactly correct. Last index is reserved for padding and is forced to 0

**Comment by sarwart** [comment]
Thank you tRosenflanz
